module.exports = {
    MAIL_USERNAME: "TU MAIL",
    MAIL_PASSWORD: "TU PASSWORD",
    OAUTH_CLIENTID: "TU ID",
    OAUTH_CLIENT_SECRET: "TU SECRET",
    OAUTH_REFRESH_TOKEN: "TU REFRESH TOKEN",
}